### ISSUE TITLE
[Question] Linux Server Stuck after NullPointerException 

### ISSUE THREAD

**Issue by rong-xiaoli** [TqLxQuanZ/DeceasedCraft#100]
Exception itself:
```text
[17:24:09] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
        at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:544) ~[server-1.18.2-20220404.173914-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:611) ~[server-1.18.2-20220404.173914-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:543) ~[server-1.18.2-20220404.173914-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pfm-common.mixins.json:PFMMixinDedicatedServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:717) ~[server-1.18.2-20220404.173914-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
[17:24:09] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot read field "playerMap" because "s" is null
        Index: 3
        Listeners:
                0: HIGHEST
                1: ASM: flaxbeard.immersivepetroleum.common.CommonEventHandler@13289823 onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                2: HIGH
                3: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                4: NORMAL
                5: net.minecraftforge.eventbus.EventBus$$Lambda$1477/0x00007fb8cc6f5fc0@43e1e3a3
                6: ASM: class shadows.placebo.util.PlaceboTaskQueue stopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                7: ASM: xaero.map.events.CommonEvents@284b457 onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                8: net.minecraftforge.eventbus.EventBus$$Lambda$1477/0x00007fb8cc6f5fc0@40992207
                9: net.minecraftforge.eventbus.EventBus$$Lambda$1477/0x00007fb8cc6f5fc0@332adbc9
                10: ASM: xaero.common.events.ForgeCommonEventHandler@1e4ad5ce onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                11: ASM: xaero.pac.common.event.CommonEventsForge@7701233c onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                12: net.minecraftforge.eventbus.EventBus$$Lambda$1477/0x00007fb8cc6f5fc0@1dc44c0b
                13: ASM: class ichttt.mods.firstaid.common.EventHandler onServerStop(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                14: ASM: com.mrcrayfish.configured.impl.simple.SimpleConfigManager@77f910eb onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                15: ASM: class noobanidus.mods.lootr.event.HandleChunk onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                16: ASM: class com.mrcrayfish.guns.common.NetworkGunManager onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                17: ASM: class snownee.kiwi.schedule.Scheduler serverStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                18: ASM: class com.tac.guns.common.NetworkRigManager onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                19: ASM: class com.tac.guns.common.NetworkGunManager onServerStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                20: ASM: class com.tac.guns.common.DelayedTask onServerStopping(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                21: ASM: class net.geforcemods.securitycraft.SCEventHandler onServerStop(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                22: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@5a1107c6 serverStopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
                23: LOWEST
                24: ASM: org.embeddedt.modernfix.forge.init.ModernFixForge@6916053e onServerDead(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
java.lang.NullPointerException: Cannot read field "playerMap" because "s" is null
        at TRANSFORMER/kubejs@1802.5.5-build.567/dev.latvian.mods.kubejs.server.KubeJSServerEventHandler.destroyServer(KubeJSServerEventHandler.java:107)
        at TRANSFORMER/kubejs@1802.5.5-build.567/dev.latvian.mods.kubejs.server.KubeJSServerEventHandler.serverStopped(KubeJSServerEventHandler.java:101)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at TRANSFORMER/architectury@4.11.93/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
        at TRANSFORMER/architectury@4.11.93/dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
        at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
        at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy154.stateChanged(Unknown Source)
        at TRANSFORMER/architectury@4.11.93/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:102)
        at net.minecraftforge.eventbus.ASMEventHandler_289_EventHandlerImplCommon_event_ServerStoppedEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.2.4/net.minecraftforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:121)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:725)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:840)

[17:24:09] [Server thread/ERROR] [minecraft/MinecraftServer]: Uncaught exception in server thread
java.lang.NullPointerException: Cannot read field "playerMap" because "s" is null
        at dev.latvian.mods.kubejs.server.KubeJSServerEventHandler.destroyServer(KubeJSServerEventHandler.java:107) ~[kubejs-forge-1802.5.5-build.567.jar%23142!/:1802.5.5-build.567] {re:classloading}
        at dev.latvian.mods.kubejs.server.KubeJSServerEventHandler.serverStopped(KubeJSServerEventHandler.java:101) ~[kubejs-forge-1802.5.5-build.567.jar%23142!/:1802.5.5-build.567] {re:classloading}
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?] {re:mixin}
        at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.11.93-forge.jar%2347!/:?] {re:classloading}
        at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-4.11.93-forge.jar%2347!/:?] {re:classloading}
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2323!/:?] {}
        at jdk.proxy3.$Proxy154.stateChanged(Unknown Source) ~[?:?] {}
        at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:102) ~[architectury-4.11.93-forge.jar%2347!/:?] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_289_EventHandlerImplCommon_event_ServerStoppedEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:121) ~[forge-1.18.2-40.2.4-universal.jar%23229!/:?] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:725) ~[server-1.18.2-20220404.173914-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:pfm.mixins.json:PFMMinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
```
And then it stucked, no more output. 
It runs on a panel, but in a terminal it's the same. 
Btw I'm going to use Velocity to connect to it, can anyone show me how?
Thanks.

**Comment by rong-xiaoli** [comment]
Ah, the Velocity's port is 25565. I should config it.

**Comment by rong-xiaoli** [comment]
Done. I mis-configured my server port.
