### ISSUE TITLE
Nature's Compass is not functional, exception is being thrown when attempting to use it

### ISSUE THREAD

**Issue by Edgeburn** [TqLxQuanZ/DeceasedCraft#77]
When trying to use the nature's compass, the list of biomes appears completely blank and we get this exception in our server console:

```
[19Apr2024 15:46:45.373] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@4a8b519b, suppressing error
java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/biome / biomesoplenty:volanic_plains]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/biome] (Stable)]
	at net.minecraft.core.Holder$Reference.m_203334_(Holder.java:146) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at com.google.common.collect.Maps$9.transformEntry(Maps.java:2053) ~[guava-31.0.1-jre.jar%2323!/:?]
	at com.google.common.collect.Maps$12.getValue(Maps.java:2101) ~[guava-31.0.1-jre.jar%2323!/:?]
	at com.chaosthedude.naturescompass.util.BiomeUtils.getAllowedBiomeKeys(BiomeUtils.java:48) ~[NaturesCompass-1.18.2-1.9.7-forge.jar%23165!/:1.18.2-1.9.7-forge]
	at com.chaosthedude.naturescompass.items.NaturesCompassItem.m_7203_(NaturesCompassItem.java:47) ~[NaturesCompass-1.18.2-1.9.7-forge.jar%23165!/:1.18.2-1.9.7-forge]
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:252) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:291) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1015) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:25) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

This is what it looks like in-game: 
![image](https://github.com/TqLxQuanZ/DeceasedCraft/assets/18710959/e20f4c83-1259-44ae-8d1e-7c8087da693b)

**Comment by TheOneDal** [comment]
should have been fixed in 5.4.3 and later

**Comment by Edgeburn** [comment]
Ah we’re still on 5.4.2. Will update and try again

**Comment by Edgeburn** [comment]
Just updated and it works correctly.
